<?php
/**
 * @var \Magento\Customer\Block\Account\Customer $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($block->customerLoggedIn()) : ?>
    <li class="link my-account-link">
        <a href="<?= /* @noEscape */ $block->getUrl('customer/account') ?>" ><?= $escaper->escapeHtml(__('My Account')) ?></a>
    </li>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
<?php endif; ?>
